---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1

inputs:
- name: booklit
- name: version
  optional: true

outputs:
- name: assets

caches:
- path: gopath/

run:
  path: booklit/ci/build
